title: 游戏攻略大全
description: 最全面的游戏攻略、技巧和指南
baseurl: "/game-guide-website"
url: "https://river-ak3.github.io/game-guide-website"
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
search:
  heading_level: 2
  rel_url_prefix: "/game-guide-website"
  button: true
heading_anchors: true
aux_links:
  GitHub: https://github.com/River-ak3/game-guide-website
footer_content: "Copyright &copy; 2026 Game Guide. Distributed under an MIT License."
compress_html:
  clippings: all
  comments: all
  endings: all
plugins:
  - jekyll-remote-theme
